<template>
  <v-data-table
    :headers="renderHeader()"
    :items="patients"
    class="elevation-1"
    item-key="bactNr"
    :search="search"
    must-sort="priority"
    hide-actions
    v-bind:pagination.sync="pagination"



  >
<template slot="items" slot-scope="props">
   <tr @click="props.expanded = !props.expanded">
        <!--The v-if statements checks the state for the tabs and sets the information accordingly !-->
                <td class="justify-center layout px-0" >
          <v-icon
            small
            class="mr-2"
            @click="editItem(props.item)"
          >
            edit
          </v-icon>
          <v-icon
            small
            @click="deleteItem(props.item)"
          >
            delete
          </v-icon>
        </td>
        <td class="text-xs-left" v-if="!headers[1].hide">
        <v-edit-dialog
            :return-value.sync="props.item.bactNr"
            lazy
            @save="save"
            @cancel="cancel"
            @open="open"
            @close="close"
          > {{ props.item.bactNr }}
                      <v-text-field
              slot="input"
              v-model="props.item.bactNr"
              label="Edit"
              single-line
              counter
            ></v-text-field>
                     </v-edit-dialog>
</td> 
        <td v-if="!headers[2].hide" class="text-xs-center">{{ props.item.altId }}</td>
        <td v-if="!headers[3].hide" class="text-xs-center">{{ props.item.priority }}</td>
        <td v-if="!headers[4].hide" class="text-xs-center">{{ props.item.pathogen }}</td>
        <td v-if="!headers[5].hide" class="text-xs-center">{{ props.item.patName }}</td>
        <td v-if="!headers[6].hide" class="text-xs-center">{{ props.item.birthdate }}</td>
        <td v-if="!headers[7].hide" class="text-xs-center">{{ props.item.entry }}</td>
        <td v-if="!headers[8].hide" class="text-xs-center">{{ props.item.abnahme }}</td>
        <td v-if="!headers[9].hide" class="text-xs-center">{{ props.item.sender }}</td>
        <td v-if="!headers[10].hide" class="text-xs-center">{{ props.item.station }}</td>
        <td v-if="!headers[11].hide" class="text-xs-center">{{ props.item.editing }}</td>
        <td v-if="!headers[12].hide" class="text-xs-center">{{ props.item.material }}</td>
        <td v-if="!headers[13].hide" class="text-xs-center">{{ props.item.ngsProject }}</td>
        <td v-if="(state<=2) && (!headers[14].hide)" class="text-xs-center">{{ props.item.dnaPrepDate }}</td>
        <td v-if="(state<=2) && (!headers[15].hide)" class="text-xs-center">{{ props.item.dnaKonz }}</td>
        <td v-if="(state<=2) && (!headers[16].hide)" class="text-xs-center">{{ props.item.dnaVisum }}</td>
        <td v-if="(state<=0) && (!headers[17].hide)" class="text-xs-center">{{ props.item.runNr }}</td>
        <td v-if="(state<=0) && (!headers[18].hide)" class="text-xs-center">{{ props.item.ngsNr }}</td>
        <td v-if="(state<=0) && (!headers[19].hide)" class="text-xs-center">{{ props.item.libType }}</td>
        <td v-if="(state<=0) && (!headers[20].hide)" class="text-xs-center">{{ props.item.libDate }}</td>
        <td v-if="(state<=0) && (!headers[21].hide)" class="text-xs-center">{{ props.item.libVisum }}</td>
        <td v-if="(state<=0) && (!headers[22].hide)" class="text-xs-center">{{ props.item.seqDate }}</td>
        <td v-if="(state<=0) && (!headers[23].hide)" class="text-xs-center">{{ props.item.ngsMachine }}</td>
        <td v-if="(state<=0) && (!headers[24].hide)" class="text-xs-center">{{ props.item.seqVisum }}</td>
        <td v-if="(state<=0) && (!headers[25].hide)" class="text-xs-center">{{ props.item.qualityVisum }}</td>
        <td v-if="(state<=0) && (!headers[26].hide)" class="text-xs-center">{{ props.item.pubID }}</td>

      </tr>
      </template>
      <template slot="expand" slot-scope="props">
      <v-card class="text-xs-center" flat>
        <v-card-text  style="background-color:grey"><b>Current BactNr.: </b>{{props.item.bactNr}} <b>| Current NGS Project:</b> {{props.item.ngsProject}}</v-card-text>
      </v-card>
    </template>
  </v-data-table>
</template>

<script>
import {bus} from '../main.js'

  export default {
    props:{
      state:Number
    },
    data: () => ({

      pagination : {'sortBy': 'priority', 'ascending': true, 'rowsPerPage': -1},
      headerindex:0,
      headers: [
        { property: 3, text: ' Actions ', value: '' , sortable:false, hide: false},
        { class:'dataSet',property: 3, text: 'Bact Nr-', sortable: true, value: 'bactNr', hide: false},
        { property: 3, text: 'Alternative ID', value: 'altId', hide: false },
        { property: 3,text: 'Priority', value: 'priority' , hide: false},
        { property: 3,text: 'Pathogen', value: 'pathogen' , hide: false},
        { class:'dataSet',property: 3,text: 'Patient', value: 'patName' , hide: false},
        { property: 3,text: 'Geburtsdatum', value: 'birthdate', hide: false },
        { property: 3,text: 'Eingang', value: 'entry', sortable: false, hide: false },
        { property: 3,text: 'Abnahme', value: 'abnahme', hide: false },
        { property: 3,text: 'Einsender', value: 'sender', hide: false },
        { property: 3,text: 'Station', value: 'station', hide: false },
        { property: 3,text: 'Bearbeitung', value: 'editing', hide: false },
        { property: 3,text: 'Material', value: 'material', hide: false },
        { property: 3,text: 'NGS-Projekt', value: 'ngsProject', hide: false },
        { property: 2,text: 'Datum DNA-Prep', value: 'dnaPrepDate', hide: false },
        { property: 2,text: 'DNA-Konz (ng/ul)', value: 'dnaKonz', hide: false },
        { property: 2,text: 'Visum DNA', value: 'dnaVisum', hide: false },
        { property: 0,text: 'Run Nummer', value: 'runNr', hide: false },
        { property: 0,text: 'NGS Nummer', value: 'ngsNr', hide: false },
        { property: 0,text: 'Library Typ', value: 'libType', hide: false },
        { property: 0,text: 'Datum Library', value: 'libDate', hide: false },
        { property: 0,text: 'Visum Library', value: 'libVisum', hide: false },
        { property: 0,text: 'Datum Sequenzierung', value: 'seqDate', hide: false },
        { property: 0,text: 'NGS Gerät', value: 'ngsMachine' , hide: false},
        { property: 0,text: 'Visum Datenqualität', value: 'qualityVisum' , hide: false},
        { property: 0,text: 'Information alte Liste', value: 'infOldList' , hide: false},
        { property: 0,text: 'Public identifier', value: 'pubID' , hide: false},
      ],
      search:'',
      tabs: null,
    patients: [],
      editedIndex: -1,
      editedPatient: {
        bactNr: '',
        infOldList: '',
        altId: '',
        priority:'',
        pathogen: '',
        patName: '',
        birthdate: '',
        entry: '',
        abnahme: '',
        sender: '',
        station: '',
        editing: '',
        material: '',
        ngsProject: '',
        dnaPrepDate: '',
        dnaKonz: '',
        dnaVisum: '',
        runNr: '',
        ngsNr: '',
        libType: '',
        libDate: '',
        libVisum: '',
        seqDate: '',
        ngsMachine: '',
        qualityVisum: '',
        pubID: '',
      },
       defaultPatient: {
        bactNr: '',
        infOldList: '',
        altId: '',
        priority:'',
        pathogen: '',
        patName: '',
        birthdate: '',
        entry: '',
        abnahme: '',
        sender: '',
        station: '',
        editing: '',
        material: '',
        ngsProject: '',
        dnaPrepDate: '',
        dnaKonz: '',
        dnaVisum: '',
        runNr: '',
        ngsNr: '',
        libType: '',
        libDate: '',
        libVisum: '',
        seqDate: '',
        ngsMachine: '',
        seqVisum:'',
        qualityVisum: '',
        pubID: '',
      }
    }),
       computed: {
      formTitle () {
        return this.editedIndex === -1 ? 'New Item' : 'Edit Item'
      },
      pages () {
        if (this.pagination.rowsPerPage == null ||
          this.pagination.totalItems == null
        ) return 0

        return Math.ceil(this.pagination.totalItems / this.pagination.rowsPerPage)
      }
    }, 

    created () {
            this.initialize()
      bus.$on('newPatientCreated', (data) =>{
      this.editedPatient = data;
      this.patients.push(this.editedPatient)
      
      });
      bus.$on('patientHasChanged', (data) =>{
      this.editedPatient = data;

      });
      bus.$on('editedIndex', (data) =>{
      this.editedIndex = data;
      this.patients.splice(this.editedIndex,1,this.editedPatient)
      });
      bus.$on('searchChanged', (data) =>{
      this.search = data;
      });
      bus.$on('hideHeader', (data) =>{
      this.headerindex = data;
      this.headers[this.headerindex].hide = !this.headers[this.headerindex].hide
      });
    },


    methods: {
      initialize () {
        this.patients = [
          {
        bactNr: '31251-18',
        infOldList: '',
        altId: '',
        priority:'A',
        pathogen: 'aciint',
        patName: 'Walter Reyes',
        birthdate: '12.03.1950',
        entry: '13.11.2018',
        abnahme: '14.11.2018',
        sender: 'Spital Basel',
        station: 'Intensiv',
        editing: '16.11.2018',
        material: 'Blut',
        ngsProject: 'NGS000012',
        dnaPrepDate: '10.11.2018',
        dnaKonz: '34',
        dnaVisum: 'BMA',
        runNr: '00542',
        ngsNr: 'NGS4230498',
        libType: 'next Generation',
        libDate: '20.08.2017',
        libVisum:'BMA',
        seqDate: '20.11.2018',
        ngsMachine: 'NextSeq',
        qualityVisum: 'BMA',
        pubID: '00003',
          },
          {
        bactNr: '301481-18',
        infOldList: '2342342',
        altId: 'ID-001',
        priority:'A',
        pathogen: 'aciint',
        patName: 'Ralph Fenstermacher',
        birthdate: '22.08.1991',
        entry: '02.09.2018',
        abnahme: '03.09.2018',
        sender: 'Spital Basel',
        station: 'Intensiv',
        editing: '04.09.2018',
        material: 'Blut',
        ngsProject: 'NGS000012',
        dnaPrepDate: '06.09.2018',
        dnaKonz: '14',
        dnaVisum: 'BMA',
        runNr: '00543',
        ngsNr: 'NGS4230498',
        libType: 'next Generation',
        libDate: '20.08.2017',
        libVisum:'BMA',
        seqDate: '16.09.2018',
        ngsMachine: 'NextSeq',
        qualityVisum: 'BMA',
        pubID: '00002',
          },  
          {
        bactNr: '101481-18',
        infOldList: '',
        altId: 'ID-004',
        priority:'A',
        pathogen: 'acinnb',
        patName: 'Julia Himmler',
        birthdate: '17.10.1956',
        entry: '14.05.2018',
        abnahme: '17.05.2018',
        sender: 'Spital Basel',
        station: 'Notfall',
        editing: '18.05.2018',
        material: 'Stuhl',
        ngsProject: 'NGS000011',
        dnaPrepDate: '23.05.2018',
        dnaKonz: '18',
        dnaVisum: 'BMA',
        runNr: '00223',
        ngsNr: 'NGS4230415',
        libType: 'next Generation',
        libDate: '20.08.2017',
        libVisum:'BMA',
        seqDate: '26.05.2018',
        ngsMachine: 'NextSeq',
        qualityVisum: 'BMA',
        pubID: '00001',
          },
          {
        bactNr: '101431-18',
        infOldList: '',
        altId: '',
        priority:'B',
        pathogen: 'actori',
        patName: 'Ines Weiss',
        birthdate: '17.10.1976',
        entry: '18.06.2018',
        abnahme: '19.06.2018',
        sender: 'Spital Zürich',
        station: 'Station A',
        editing: '20.06.2018',
        material: 'Auswurf',
        ngsProject: 'NGS000015',
        dnaPrepDate: '23.06.2018',
        dnaKonz: '22',
        dnaVisum: 'BMA',
        runNr: '00223',
        ngsNr: 'NGS4230415',
        libType: 'next Generation',
        libDate: '20.08.2017',
        libVisum:'BMA',
        seqDate: '26.05.2018',
        ngsMachine: 'NextSeq',
        qualityVisum: 'BMA',
        pubID: '00004',
          }, 
          {
        bactNr: '101435-18',
        infOldList: '',
        altId: 'ID-056',
        priority:'A',
        pathogen: 'actori',
        patName: 'Jonas Waechter',
        birthdate: '17.10.1986',
        entry: '14.06.2018',
        abnahme: '15.06.2018',
        sender: 'Spital Zürich',
        station: 'Orthopädie',
        editing: '20.06.2018',
        material: 'Bronchialsekret',
        ngsProject: 'NGS000012',
        dnaPrepDate: '21.06.2018',
        dnaKonz: '27',
        dnaVisum: 'BMA',
        runNr: '00223',
        ngsNr: 'NGS4230415',
        libType: 'Nextera XT',
        libDate: '05.02.2016',
        libVisum:'BMA',
        seqDate: '08.03.2018',
        ngsMachine: 'NextSeq',
        qualityVisum: 'BMA',
        pubID: '00004',
          }, 
          {
        bactNr: '151497-18',
        infOldList: '',
        altId: 'ID-784',
        priority:'A',
        pathogen: 'actori',
        patName: 'Patrick Ostermann',
        birthdate: '10.02.1989',
        entry: '03.01.2018',
        abnahme: '04.01.2018',
        sender: 'Spital Basel',
        station: 'Dermatologie',
        editing: '06.01.2018',
        material: 'Biopsie',
        ngsProject: 'NGS001238',
        dnaPrepDate: '10.01.2018',
        dnaKonz: '43',
        dnaVisum: 'BMA',
        runNr: '00273',
        ngsNr: 'NGS4230419',
        libType: 'Nextera XT',
        libDate: '01.12.2017',
        libVisum:'BMA',
        seqDate: '10.01.2018',
        ngsMachine: 'NextSeq',
        qualityVisum: 'BMA',
        pubID: '00004',
          }, 
          {
        bactNr: '127947-18',
        infOldList: '',
        altId: '',
        priority:'B',
        pathogen: 'actori',
        patName: 'Lena Kluge',
        birthdate: '15.06.1941',
        entry: '05.01.2018',
        abnahme: '06.01.2018',
        sender: 'Inselspital Bern',
        station: 'Palliativmedizin ',
        editing: '12.01.2018',
        material: 'Stuhl',
        ngsProject: 'NGS001738',
        dnaPrepDate: '14.01.2018',
        dnaKonz: '33',
        dnaVisum: 'BMA',
        runNr: '00473',
        ngsNr: 'NGS4233419',
        libType: 'Nextera XT',
        libDate: '01.12.2017',
        libVisum:'BMA',
        seqDate: '10.01.2018',
        ngsMachine: 'NextSeq',
        qualityVisum: 'BMA',
        pubID: '00014',
          }, 
          {
        bactNr: '111497-18',
        infOldList: '',
        altId: 'DA23d34',
        priority:'A',
        pathogen: 'pkt',
        patName: 'Benjamin Grunewald',
        birthdate: '13.02.1973',
        entry: '12.03.2018',
        abnahme: '13.03.2018',
        sender: 'Spital Zürich',
        station: 'Mund-, KieferChirurgie',
        editing: '15.03.2018',
        material: 'Sputum',
        ngsProject: 'NGS007238',
        dnaPrepDate: '19.03.2018',
        dnaKonz: '52',
        dnaVisum: 'BMA',
        runNr: '00973',
        ngsNr: 'NGS4238419',
        libType: 'Nextera XT',
        libDate: '01.02.2018',
        libVisum:'BMA',
        seqDate: '25.01.2018',
        ngsMachine: 'NextSeq',
        qualityVisum: 'BMA',
        pubID: '01232',
          }, 
          {
        bactNr: '159027-18',
        infOldList: '',
        altId: '',
        priority:'B',
        pathogen: 'strebg',
        patName: 'Swen Mauer',
        birthdate: '28.04.1969',
        entry: '13.07.2018',
        abnahme: '16.07.2018',
        sender: 'Spital Basel',
        station: 'Neurochirurgie',
        editing: '22.07.2018',
        material: 'Biopsie',
        ngsProject: 'NGS011238',
        dnaPrepDate: '25.07.2018',
        dnaKonz: '63',
        dnaVisum: 'BMA',
        runNr: '02273',
        ngsNr: 'NGS4230400',
        libType: 'Nextera XT',
        libDate: '24.05.2018',
        libVisum:'BMA',
        seqDate: '28.07.2018',
        ngsMachine: 'NextSeq',
        qualityVisum: 'BMA',
        pubID: '00314',
          }, 
          {
        bactNr: '127347-17',
        infOldList: '',
        altId: '',
        priority:'B',
        pathogen: 'clodif',
        patName: 'Thomas Shuster',
        birthdate: '28.04.1973',
        entry: '16.07.2018',
        abnahme: '16.07.2018',
        sender: 'Spital Basel',
        station: 'Station B',
        editing: '21.07.2018',
        material: 'Sputum',
        ngsProject: 'NGS012238',
        dnaPrepDate: '25.07.2018',
        dnaKonz: '34',
        dnaVisum: 'BMA',
        runNr: '01263',
        ngsNr: 'NGS4210400',
        libType: 'Nextera XT',
        libDate: '24.05.2018',
        libVisum:'BMA',
        seqDate: '27.07.2018',
        ngsMachine: 'NextSeq',
        qualityVisum: 'BMA',
        pubID: '00315',
          }, 
          {
        bactNr: '168497-18',
        infOldList: '',
        altId: '',
        priority:'A',
        pathogen: 'strenh',
        patName: 'Manuela Dörbier',
        birthdate: '28.04.1989',
        entry: '16.08.2018',
        abnahme: '16.08.2018',
        sender: 'Spital Basel',
        station: 'Gynäkologie',
        editing: '21.08.2018',
        material: 'Abstrich',
        ngsProject: 'NGS012238',
        dnaPrepDate: '25.08.2018',
        dnaKonz: '38',
        dnaVisum: 'BMA',
        runNr: '01213',
        ngsNr: 'NGS4510400',
        libType: 'Nextera XT',
        libDate: '24.05.2018',
        libVisum:'BMA',
        seqDate: '27.07.2018',
        ngsMachine: 'NextSeq',
        qualityVisum: 'BMA',
        pubID: '00316',
          }, 
           {
        bactNr: '311281-18',
        infOldList: '',
        altId: '',
        priority:'B',
        pathogen: 'aciint',
        patName: 'Christian Schulz',
        birthdate: '12.06.1950',
        entry: '12.03.2018',
        abnahme: '13.03.2018',
        sender: 'Spital Zürich',
        station: 'Intensiv',
        editing: '11.03.2018',
        material: 'Blut',
        ngsProject: 'NGS000142',
        dnaPrepDate: '15.03.2018',
        dnaKonz: '54',
        dnaVisum: 'BMA',
        runNr: '00142',
        ngsNr: 'NGS4243198',
        libType: 'next Generation',
        libDate: '20.08.2017',
        libVisum:'BMA',
        seqDate: '20.01.2017',
        ngsMachine: 'NextSeq',
        qualityVisum: 'BMA',
        pubID: '00734',
          },
          {
        bactNr: '601481-18',
        infOldList: '',
        altId: '',
        priority:'B',
        pathogen: 'ecoli',
        patName: 'Mike Schaefer',
        birthdate: '22.08.1991',
        entry: '03.09.2018',
        abnahme: '02.09.2018',
        sender: 'Inselspital Bern',
        station: 'Intensiv',
        editing: '04.09.2018',
        material: 'Blut',
        ngsProject: 'NGS000012',
        dnaPrepDate: '06.09.2018',
        dnaKonz: '14',
        dnaVisum: 'BMA',
        runNr: '00543',
        ngsNr: 'NGS4230498',
        libType: 'next Generation',
        libDate: '20.08.2017',
        libVisum:'BMA',
        seqDate: '16.09.2018',
        ngsMachine: 'NextSeq',
        qualityVisum: 'BMA',
        pubID: '00002',
          },  
          {
        bactNr: '121481-18',
        infOldList: '',
        altId: '',
        priority:'A',
        pathogen: 'ecoli',
        patName: 'Dieter Frueh',
        birthdate: '17.10.1956',
        entry: '14.05.2018',
        abnahme: '17.05.2018',
        sender: 'Spital Basel',
        station: 'Notfall',
        editing: '18.05.2018',
        material: 'Stuhl',
        ngsProject: 'NGS020011',
        dnaPrepDate: '23.05.2018',
        dnaKonz: '18',
        dnaVisum: 'BMA',
        runNr: '00223',
        ngsNr: 'NGS4230415',
        libType: 'next Generation',
        libDate: '20.08.2017',
        libVisum:'BMA',
        seqDate: '26.05.2018',
        ngsMachine: 'NextSeq',
        qualityVisum: 'BMA',
        pubID: '30501',
          },
          {
        bactNr: '101439-17',
        infOldList: 'NG30223',
        altId: 'ID-004',
        priority:'A',
        pathogen: 'stremo',
        patName: 'Tom Papst',
        birthdate: '17.10.1982',
        entry: '22.06.2018',
        abnahme: '23.06.2018',
        sender: 'Spital Zürich',
        station: 'Station A',
        editing: '25.06.2018',
        material: 'Auswurf',
        ngsProject: 'NGS000015',
        dnaPrepDate: '23.06.2018',
        dnaKonz: '28',
        dnaVisum: 'BMA',
        runNr: '00223',
        ngsNr: 'NGS4230415',
        libType: 'next Generation',
        libDate: '20.08.2017',
        libVisum:'BMA',
        seqDate: '26.05.2018',
        ngsMachine: 'NextSeq',
        qualityVisum: 'BMA',
        pubID: '00354',
          }, 
          {
        bactNr: '191435-18',
        infOldList: '',
        altId: 'NGS-156',
        priority:'A',
        pathogen: 'actori',
        patName: 'Thorsten Muench',
        birthdate: '17.10.1986',
        entry: '14.06.2018',
        abnahme: '15.06.2018',
        sender: 'Spital Zürich',
        station: 'Orthopädie',
        editing: '20.06.2018',
        material: 'Bronchialsekret',
        ngsProject: 'NGS000012',
        dnaPrepDate: '21.06.2018',
        dnaKonz: '25',
        dnaVisum: 'BMA',
        runNr: '00223',
        ngsNr: 'NGS4230415',
        libType: 'Nextera XT',
        libDate: '05.02.2016',
        libVisum:'BMA',
        seqDate: '08.03.2018',
        ngsMachine: 'NextSeq',
        qualityVisum: 'BMA',
        pubID: '01504',
          }, 
          {
        bactNr: '168397-18',
        infOldList: '',
        altId: '',
        priority:'A',
        pathogen: 'stregc',
        patName: 'Sandra Fink',
        birthdate: '10.02.1989',
        entry: '03.01.2018',
        abnahme: '04.01.2018',
        sender: 'Spital Basel',
        station: 'Dermatologie',
        editing: '06.01.2018',
        material: 'Biopsie',
        ngsProject: 'NGS001238',
        dnaPrepDate: '10.01.2018',
        dnaKonz: '43',
        dnaVisum: 'BMA',
        runNr: '00745',
        ngsNr: 'NGS4230419',
        libType: 'Nextera XT',
        libDate: '01.12.2017',
        libVisum:'BMA',
        seqDate: '10.01.2018',
        ngsMachine: 'NextSeq',
        qualityVisum: 'BMA',
        pubID: '57004',
          }, 
          {
        bactNr: '101457-18',
        infOldList: '',
        altId: '',
        priority:'A',
        pathogen: 'acihae',
        patName: 'Barbara Eisenhower',
        birthdate: '15.06.1963',
        entry: '05.01.2018',
        abnahme: '06.01.2018',
        sender: 'Inselspital Bern',
        station: 'Palliativmedizin ',
        editing: '12.01.2018',
        material: 'Stuhl',
        ngsProject: 'NGS001748',
        dnaPrepDate: '14.01.2018',
        dnaKonz: '33',
        dnaVisum: 'BMA',
        runNr: '01473',
        ngsNr: 'NGS4233419',
        libType: 'Nextera XT',
        libDate: '01.12.2017',
        libVisum:'BMA',
        seqDate: '10.01.2018',
        ngsMachine: 'NextSeq',
        qualityVisum: 'BMA',
        pubID: '00854',
          }, 
          {
        bactNr: '129497-18',
        infOldList: '',
        altId: '',
        priority:'A',
        pathogen: 'pkt',
        patName: 'Peter Abend',
        birthdate: '13.02.1973',
        entry: '12.03.2018',
        abnahme: '13.03.2018',
        sender: 'Spital Zürich',
        station: 'Mund-, KieferChirurgie',
        editing: '15.03.2018',
        material: 'Sputum',
        ngsProject: 'NGS007238',
        dnaPrepDate: '19.03.2018',
        dnaKonz: '52',
        dnaVisum: 'BMA',
        runNr: '01973',
        ngsNr: 'NGS4238419',
        libType: 'Nextera XT',
        libDate: '01.02.2018',
        libVisum:'BMA',
        seqDate: '25.01.2018',
        ngsMachine: 'NextSeq',
        qualityVisum: 'BMA',
        pubID: '01978',
          }, 
          {
        bactNr: '978597-18',
        infOldList: '',
        altId: '',
        priority:'B',
        pathogen: 'ecoli',
        patName: 'Manuela Fuchs',
        birthdate: '28.04.1969',
        entry: '13.07.2018',
        abnahme: '16.07.2018',
        sender: 'Spital Basel',
        station: 'Neurochirurgie',
        editing: '22.07.2018',
        material: 'Biopsie',
        ngsProject: 'NGS011238',
        dnaPrepDate: '25.07.2018',
        dnaKonz: '63',
        dnaVisum: 'BMA',
        runNr: '02973',
        ngsNr: 'NGS4234460',
        libType: 'Nextera XT',
        libDate: '24.05.2018',
        libVisum:'BMA',
        seqDate: '28.07.2018',
        ngsMachine: 'NextSeq',
        qualityVisum: 'BMA',
        pubID: '07319',
          }, 
           {
        bactNr: '178991-18',
        infOldList: '',
        altId: '',
        priority:'B',
        pathogen: 'clodif',
        patName: 'Ursula Fried',
        birthdate: '28.04.1973',
        entry: '16.07.2018',
        abnahme: '16.07.2018',
        sender: 'Spital Basel',
        station: 'Station B',
        editing: '21.07.2018',
        material: 'Sputum',
        ngsProject: 'NGS015238',
        dnaPrepDate: '25.07.2018',
        dnaKonz: '34',
        dnaVisum: 'BMA',
        runNr: '01263',
        ngsNr: 'NGS4210490',
        libType: 'Nextera XT',
        libDate: '24.05.2018',
        libVisum:'BMA',
        seqDate: '27.07.2018',
        ngsMachine: 'NextSeq',
        qualityVisum: 'BMA',
        pubID: '09315',
          }, 
          {
        bactNr: '683057-18',
        infOldList: '',
        altId: '',
        priority:'B',
        pathogen: 'strenh',
        patName: 'Anja Möller',
        birthdate: '28.04.1989',
        entry: '16.08.2018',
        abnahme: '16.08.2018',
        sender: 'Spital Basel',
        station: 'Gynäkologie',
        editing: '21.08.2018',
        material: 'Abstrich',
        ngsProject: 'NGS012238',
        dnaPrepDate: '25.08.2018',
        dnaKonz: '38',
        dnaVisum: 'BMA',
        runNr: '01213',
        ngsNr: 'NGS4514400',
        libType: 'Nextera XT',
        libDate: '24.05.2018',
        libVisum:'BMA',
        seqDate: '27.07.2018',
        ngsMachine: 'NextSeq',
        qualityVisum: 'BMA',
        pubID: '01316',
          },
          {
        bactNr: '32252-18',
        infOldList: '',
        altId: '',
        priority:'B',
        pathogen: 'stregp',
        patName: 'Tim Schäfer',
        birthdate: '12.03.1950',
        entry: '13.11.2018',
        abnahme: '14.11.2018',
        sender: 'Spital Basel',
        station: 'Intensiv',
        editing: '16.11.2018',
        material: 'Blut',
        ngsProject: 'NGS000012',
        dnaPrepDate: '10.11.2018',
        dnaKonz: '34',
        dnaVisum: 'BMA',
        runNr: '',
        ngsNr: 'NGS4230498',
        libType: 'next Generation',
        libDate: '20.08.2017',
        libVisum:'BMA',
        seqDate: '20.11.2018',
        ngsMachine: 'NextSeq',
        qualityVisum: 'BMA',
        pubID: '03053',
          },
          {
        bactNr: '911481-18',
        infOldList: '2342342',
        altId: 'ID-001',
        priority:'B',
        pathogen: 'stremo',
        patName: 'Robert Ostermann',
        birthdate: '22.08.1991',
        entry: '02.09.2018',
        abnahme: '03.09.2018',
        sender: 'Spital Basel',
        station: 'Intensiv',
        editing: '04.09.2018',
        material: 'Blut',
        ngsProject: 'NGS000012',
        dnaPrepDate: '06.09.2018',
        dnaKonz: '14',
        dnaVisum: 'BMA',
        runNr: '00543',
        ngsNr: 'NGS4230498',
        libType: 'next Generation',
        libDate: '20.08.2017',
        libVisum:'BMA',
        seqDate: '16.09.2018',
        ngsMachine: 'NextSeq',
        qualityVisum: 'BMA',
        pubID: '00002',
          },  
          {
        bactNr: '100001-18',
        infOldList: '',
        altId: 'ID-004',
        priority:'B',
        pathogen: 'acinnb',
        patName: 'Julia Baader',
        birthdate: '17.10.1956',
        entry: '14.05.2018',
        abnahme: '17.05.2018',
        sender: 'Spital Basel',
        station: 'Notfall',
        editing: '18.05.2018',
        material: 'Stuhl',
        ngsProject: 'NGS002011',
        dnaPrepDate: '23.05.2018',
        dnaKonz: '18',
        dnaVisum: 'BMA',
        runNr: '00223',
        ngsNr: 'NGS4230415',
        libType: 'next Generation',
        libDate: '20.08.2017',
        libVisum:'BMA',
        seqDate: '26.05.2018',
        ngsMachine: 'NextSeq',
        qualityVisum: 'BMA',
        pubID: '06501',
          },
          {
        bactNr: '113431-18',
        infOldList: '',
        altId: '',
        priority:'C',
        pathogen: 'actori',
        patName: 'Ursula Propst',
        birthdate: '17.10.1976',
        entry: '18.06.2018',
        abnahme: '19.06.2018',
        sender: 'Spital Zürich',
        station: 'Station A',
        editing: '20.06.2018',
        material: 'Auswurf',
        ngsProject: 'NGS000015',
        dnaPrepDate: '23.06.2018',
        dnaKonz: '22',
        dnaVisum: 'BMA',
        runNr: '00223',
        ngsNr: 'NGS4230415',
        libType: 'next Generation',
        libDate: '20.08.2017',
        libVisum:'BMA',
        seqDate: '26.05.2018',
        ngsMachine: 'NextSeq',
        qualityVisum: 'BMA',
        pubID: '056404',
          }, 
          {
        bactNr: '149765-18',
        infOldList: '',
        altId: '',
        priority:'A',
        pathogen: 'actori',
        patName: 'Jürgen Vogel',
        birthdate: '17.10.1986',
        entry: '14.06.2018',
        abnahme: '15.06.2018',
        sender: 'Spital Zürich',
        station: 'Orthopädie',
        editing: '20.06.2018',
        material: 'Bronchialsekret',
        ngsProject: 'NGS004612',
        dnaPrepDate: '21.06.2018',
        dnaKonz: '27',
        dnaVisum: 'BMA',
        runNr: '00223',
        ngsNr: 'NGS4230415',
        libType: 'Nextera XT',
        libDate: '05.02.2016',
        libVisum:'BMA',
        seqDate: '08.03.2018',
        ngsMachine: 'NextSeq',
        qualityVisum: 'BMA',
        pubID: '002344',
          }, 
          {
        bactNr: '13957-18',
        infOldList: '',
        altId: '',
        priority:'A',
        pathogen: 'actori',
        patName: 'Susanne Klein',
        birthdate: '10.02.1989',
        entry: '03.01.2018',
        abnahme: '04.01.2018',
        sender: 'Spital Basel',
        station: 'Dermatologie',
        editing: '06.01.2018',
        material: 'Biopsie',
        ngsProject: 'NGS001238',
        dnaPrepDate: '10.01.2018',
        dnaKonz: '43',
        dnaVisum: 'BMA',
        runNr: '00273',
        ngsNr: 'NGS4230419',
        libType: 'Nextera XT',
        libDate: '01.12.2017',
        libVisum:'BMA',
        seqDate: '10.01.2018',
        ngsMachine: 'NextSeq',
        qualityVisum: 'BMA',
        pubID: '684344',
          }, 
          {
        bactNr: '125977-18',
        infOldList: '',
        altId: '',
        priority:'A',
        pathogen: 'actori',
        patName: 'Lukas Hofmann',
        birthdate: '15.06.1941',
        entry: '05.01.2018',
        abnahme: '06.01.2018',
        sender: 'Inselspital Bern',
        station: 'Palliativmedizin ',
        editing: '12.01.2018',
        material: 'Stuhl',
        ngsProject: 'NGS001738',
        dnaPrepDate: '14.01.2018',
        dnaKonz: '33',
        dnaVisum: 'BMA',
        runNr: '00473',
        ngsNr: 'NGS4233419',
        libType: 'Nextera XT',
        libDate: '01.12.2017',
        libVisum:'BMA',
        seqDate: '10.01.2018',
        ngsMachine: 'NextSeq',
        qualityVisum: 'BMA',
        pubID: '498632',
          }, 
          {
        bactNr: '125397-18',
        infOldList: '',
        altId: 'DA23d34',
        priority:'A',
        pathogen: 'pkt',
        patName: 'Eric Schuster',
        birthdate: '13.02.1973',
        entry: '12.03.2018',
        abnahme: '13.03.2018',
        sender: 'Spital Zürich',
        station: 'Mund-, KieferChirurgie',
        editing: '15.03.2018',
        material: 'Sputum',
        ngsProject: 'NGS007238',
        dnaPrepDate: '19.03.2018',
        dnaKonz: '52',
        dnaVisum: 'BMA',
        runNr: '00973',
        ngsNr: 'NGS4238419',
        libType: 'Nextera XT',
        libDate: '01.02.2018',
        libVisum:'BMA',
        seqDate: '25.01.2018',
        ngsMachine: 'NextSeq',
        qualityVisum: 'BMA',
        pubID: '0123682',
          }, 
          {
        bactNr: '159927-17',
        infOldList: 'NG30223',
        altId: 'ID-004',
        priority:'C',
        pathogen: 'strebg',
        patName: 'Susanne Dresdner',
        birthdate: '28.04.1969',
        entry: '13.07.2018',
        abnahme: '16.07.2018',
        sender: 'Spital Basel',
        station: 'Neurochirurgie',
        editing: '22.07.2018',
        material: 'Biopsie',
        ngsProject: 'NGS311238',
        dnaPrepDate: '25.07.2018',
        dnaKonz: '63',
        dnaVisum: 'BMA',
        runNr: '02273',
        ngsNr: 'NGS4230400',
        libType: 'Nextera XT',
        libDate: '24.05.2018',
        libVisum:'BMA',
        seqDate: '28.07.2018',
        ngsMachine: 'NextSeq',
        qualityVisum: 'BMA',
        pubID: '0345914',
          }, 
          {
        bactNr: '127237-17',
        infOldList: '',
        altId: '',
        priority:'C',
        pathogen: 'clodif',
        patName: 'Martin Kuhn',
        birthdate: '28.04.1973',
        entry: '16.07.2018',
        abnahme: '16.07.2018',
        sender: 'Spital Basel',
        station: 'Station B',
        editing: '21.07.2018',
        material: 'Sputum',
        ngsProject: 'NGS012238',
        dnaPrepDate: '25.07.2018',
        dnaKonz: '34',
        dnaVisum: 'BMA',
        runNr: '01263',
        ngsNr: 'NGS4210400',
        libType: 'Nextera XT',
        libDate: '24.05.2018',
        libVisum:'BMA',
        seqDate: '27.07.2018',
        ngsMachine: 'NextSeq',
        qualityVisum: 'BMA',
        pubID: '0036715',
          }, 
          {
        bactNr: '168427-18',
        infOldList: '',
        altId: '',
        priority:'C',
        pathogen: 'strenh',
        patName: 'Kathrin Bauer',
        birthdate: '28.04.1989',
        entry: '16.08.2018',
        abnahme: '16.08.2018',
        sender: 'Spital Basel',
        station: 'Gynäkologie',
        editing: '21.08.2018',
        material: 'Abstrich',
        ngsProject: 'NGS012238',
        dnaPrepDate: '25.08.2018',
        dnaKonz: '38',
        dnaVisum: 'BMA',
        runNr: '01213',
        ngsNr: 'NGS4510400',
        libType: 'Nextera XT',
        libDate: '24.05.2018',
        libVisum:'BMA',
        seqDate: '27.07.2018',
        ngsMachine: 'NextSeq',
        qualityVisum: 'BMA',
        pubID: '00316',
          }, 
           {
        bactNr: '583958-18',
        infOldList: '',
        altId: '',
        priority:'C',
        pathogen: 'aciint',
        patName: 'Jens Konig',
        birthdate: '12.06.1950',
        entry: '12.03.2018',
        abnahme: '13.03.2018',
        sender: 'Spital Zürich',
        station: 'Intensiv',
        editing: '11.03.2018',
        material: 'Blut',
        ngsProject: 'NGS000142',
        dnaPrepDate: '15.03.2018',
        dnaKonz: '54',
        dnaVisum: 'BMA',
        runNr: '00142',
        ngsNr: 'NGS4243198',
        libType: 'next Generation',
        libDate: '20.08.2017',
        libVisum:'BMA',
        seqDate: '20.01.2017',
        ngsMachine: 'NextSeq',
        qualityVisum: 'BMA',
        pubID: '056734',
          },
          {
        bactNr: '601401-18',
        infOldList: '',
        altId: '',
        priority:'C',
        pathogen: 'ecoli',
        patName: 'Lukas Pabst',
        birthdate: '22.08.1991',
        entry: '03.09.2018',
        abnahme: '02.09.2018',
        sender: 'Inselspital Bern',
        station: 'Intensiv',
        editing: '04.09.2018',
        material: 'Blut',
        ngsProject: 'NGS000012',
        dnaPrepDate: '06.09.2018',
        dnaKonz: '14',
        dnaVisum: 'BMA',
        runNr: '00543',
        ngsNr: 'NGS4230498',
        libType: 'next Generation',
        libDate: '20.08.2017',
        libVisum:'BMA',
        seqDate: '16.09.2018',
        ngsMachine: 'NextSeq',
        qualityVisum: 'BMA',
        pubID: '543002',
          },  
          {
        bactNr: '126881-18',
        infOldList: '',
        altId: 'ID-074',
        priority:'C',
        pathogen: 'ecoli',
        patName: 'Lucas Gloeckner',
        birthdate: '17.10.1956',
        entry: '14.05.2018',
        abnahme: '17.05.2018',
        sender: 'Spital Basel',
        station: 'Notfall',
        editing: '18.05.2018',
        material: 'Stuhl',
        ngsProject: 'NGS020011',
        dnaPrepDate: '23.05.2018',
        dnaKonz: '18',
        dnaVisum: 'BMA',
        runNr: '00223',
        ngsNr: 'NGS4230415',
        libType: 'next Generation',
        libDate: '20.08.2017',
        libVisum:'BMA',
        seqDate: '26.05.2018',
        ngsMachine: 'NextSeq',
        qualityVisum: 'BMA',
        pubID: '308961',
          },
          {
        bactNr: '101959-17',
        infOldList: 'NG30223',
        altId: 'ID404',
        priority:'C',
        pathogen: 'stremo',
        patName: 'Dominik Faerber',
        birthdate: '17.10.1982',
        entry: '22.06.2018',
        abnahme: '23.06.2018',
        sender: 'Spital Zürich',
        station: 'Station A',
        editing: '25.06.2018',
        material: 'Auswurf',
        ngsProject: 'NGS000015',
        dnaPrepDate: '23.06.2018',
        dnaKonz: '28',
        dnaVisum: 'BMA',
        runNr: '00223',
        ngsNr: 'NGS4230415',
        libType: 'next Generation',
        libDate: '20.08.2017',
        libVisum:'BMA',
        seqDate: '26.05.2018',
        ngsMachine: 'NextSeq',
        qualityVisum: 'BMA',
        pubID: '008644',
          }, 
          {
        bactNr: '191575-18',
        infOldList: '',
        altId: 'NGS-156',
        pathogen: 'actori',
        patName: 'Kristin Kastner',
        birthdate: '17.10.1986',
        entry: '14.06.2018',
        abnahme: '15.06.2018',
        sender: 'Spital Zürich',
        station: 'Orthopädie',
        editing: '20.06.2018',
        material: 'Bronchialsekret',
        ngsProject: 'NGS000012',
        dnaPrepDate: '21.06.2018',
        dnaKonz: '25',
        dnaVisum: 'BMA',
        runNr: '00223',
        ngsNr: 'NGS4230415',
        libType: 'Nextera XT',
        libDate: '05.02.2016',
        libVisum:'BMA',
        seqDate: '08.03.2018',
        ngsMachine: 'NextSeq',
        qualityVisum: 'BMA',
        pubID: '015674',
          }, 
          {
        bactNr: '168399-18',
        infOldList: 'NG30223',
        altId: '',
        priority:'C',
        pathogen: 'stregc',
        patName: 'Simone Schultheiss',
        birthdate: '10.02.1989',
        entry: '03.01.2018',
        abnahme: '04.01.2018',
        sender: 'Spital Basel',
        station: 'Dermatologie',
        editing: '06.01.2018',
        material: 'Biopsie',
        ngsProject: 'NGS001238',
        dnaPrepDate: '10.01.2018',
        dnaKonz: '43',
        dnaVisum: 'BMA',
        runNr: '00745',
        ngsNr: 'NGS4230419',
        libType: 'Nextera XT',
        libDate: '01.12.2017',
        libVisum:'BMA',
        seqDate: '10.01.2018',
        ngsMachine: 'NextSeq',
        qualityVisum: 'BMA',
        pubID: '68403',
          }, 
          {
        bactNr: '106457-18',
        infOldList: 'NG30223',
        altId: 'ID-004',
        priority:'C',
        pathogen: 'acihae',
        patName: 'Kevin Busch',
        birthdate: '15.06.1963',
        entry: '05.01.2018',
        abnahme: '06.01.2018',
        sender: 'Inselspital Bern',
        station: 'Palliativmedizin ',
        editing: '12.01.2018',
        material: 'Stuhl',
        ngsProject: 'NGS001748',
        dnaPrepDate: '14.01.2018',
        dnaKonz: '33',
        dnaVisum: 'BMA',
        runNr: '01473',
        ngsNr: 'NGS4233419',
        libType: 'Nextera XT',
        libDate: '01.12.2017',
        libVisum:'BMA',
        seqDate: '10.01.2018',
        ngsMachine: 'NextSeq',
        qualityVisum: 'BMA',
        pubID: '40854',
          }, 
          {
        bactNr: '125617-18',
        infOldList: 'DA23d34',
        altId: 'DA23d34',
        priority:'C',
        pathogen: 'pkt',
        patName: 'Agatha Ásgeirsdóttir',
        birthdate: '13.02.1973',
        entry: '12.03.2018',
        abnahme: '13.03.2018',
        sender: 'Spital Zürich',
        station: 'Mund-, KieferChirurgie',
        editing: '15.03.2018',
        material: 'Sputum',
        ngsProject: 'NGS007238',
        dnaPrepDate: '19.03.2018',
        dnaKonz: '52',
        dnaVisum: 'BMA',
        runNr: '01973',
        ngsNr: 'NGS4238419',
        libType: 'Nextera XT',
        libDate: '01.02.2018',
        libVisum:'BMA',
        seqDate: '25.01.2018',
        ngsMachine: 'NextSeq',
        qualityVisum: 'BMA',
        pubID: '01957',
          }, 
          {
        bactNr: '972597-18',
        infOldList: 'NG30223',
        altId: 'ID-004',
        priority:'C',
        pathogen: 'ecoli',
        patName: 'Hrefna Guðnadóttir',
        birthdate: '28.04.1969',
        entry: '13.07.2018',
        abnahme: '16.07.2018',
        sender: 'Spital Basel',
        station: 'Neurochirurgie',
        editing: '22.07.2018',
        material: 'Biopsie',
        ngsProject: 'NGS011238',
        dnaPrepDate: '25.07.2018',
        dnaKonz: '63',
        dnaVisum: 'BMA',
        runNr: '02973',
        ngsNr: 'NGS4274460',
        libType: 'Nextera XT',
        libDate: '24.05.2018',
        libVisum:'BMA',
        seqDate: '28.07.2018',
        ngsMachine: 'NextSeq',
        qualityVisum: 'BMA',
        pubID: '07619',
          }, 
           {
        bactNr: '178911-18',
        infOldList: '',
        altId: '',
        priority:'C',
        pathogen: 'clodif',
        patName: 'Thibaut Audibert',
        birthdate: '28.04.1973',
        entry: '16.07.2018',
        abnahme: '16.07.2018',
        sender: 'Spital Basel',
        station: 'Station B',
        editing: '21.07.2018',
        material: 'Sputum',
        ngsProject: 'NGS015238',
        dnaPrepDate: '25.07.2018',
        dnaKonz: '34',
        dnaVisum: 'BMA',
        runNr: '01263',
        ngsNr: 'NGS4210490',
        libType: 'Nextera XT',
        libDate: '24.05.2018',
        libVisum:'BMA',
        seqDate: '27.07.2018',
        ngsMachine: 'NextSeq',
        qualityVisum: 'BMA',
        pubID: '49315',
          }, 
          {
        bactNr: '683157-18',
        infOldList: '',
        altId: '',
        priority:'B',
        pathogen: 'strenh',
        patName: 'Alexandrin Reault',
        birthdate: '28.04.1989',
        entry: '16.08.2018',
        abnahme: '16.08.2018',
        sender: 'Spital Basel',
        station: 'Gynäkologie',
        editing: '21.08.2018',
        material: 'Abstrich',
        ngsProject: 'NGS012238',
        dnaPrepDate: '25.08.2018',
        dnaKonz: '38',
        dnaVisum: 'BMA',
        runNr: '01213',
        ngsNr: 'NGS4514400',
        libType: 'Nextera XT',
        libDate: '24.05.2018',
        libVisum:'BMA',
        seqDate: '27.07.2018',
        ngsMachine: 'NextSeq',
        qualityVisum: 'BMA',
        pubID: '67316',
          }               
        ]
      },
          editItem (item) {
        //ursprünglicher Code der den PatID mitgibt!
        this.editedIndex = this.patients.indexOf(item)
        this.editedPatient = Object.assign({}, item)

        bus.$emit('openFormular', true) // emit the event to the bus
        bus.$emit('editedIndex', this.editedIndex)
        bus.$emit('editedPatient',this.editedPatient)

      },


      deleteItem (item) {
        const index = this.patients.indexOf(item)
        confirm('Are you sure you want to delete this dataset?') && this.patients.splice(index, 1)
      },

      /*This method grabs all the headers in header[] and checks its property, compares it with
      the state from the tab (which get provided by the Tableframe) and sets the tableheaders
      accordingly */
      renderHeader(){
        return this.headers.filter(h => (h.property>= this.state)).filter(h => h.hide == false)
      },
      save () {
        this.snack = true
        this.snackColor = 'success'
        this.snackText = 'Data saved'
      },
      cancel () {
        this.snack = true
        this.snackColor = 'error'
        this.snackText = 'Canceled'
      },
      open () {
        this.snack = true
        this.snackColor = 'info'
        this.snackText = 'Dialog opened'
      },
      close () {
        console.log('Dialog closed')
      }
    }
  }
  </script>

<style>
.dataSet{
  max-height: 50px;
  min-width: 130px;
}
</style>
